version: '3.8'
services:
  personal-website:
    restart: unless-stopped
    ## environment:
    ##  - Test
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: production
    image: vanderbrandung/personal-website:latest
    ports:
      - '7000:3000'
    networks:
      - scoobydoo
networks:
  scoobydoo:
    external: true
