version: '3.8'
services:
  website:
    restart: unless-stopped
   ## environment:
    ##  - Test
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: production
    ##image: registry.gitlab.com/onecalendar/onecalendar/app_pre_prod_frontend
    ports:
      - '7000:3000'
    networks:
      - scoobydoo
networks:
  scoobydoo:
    external: true
