name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - development
      - feature-test-pipeline

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker Image
  #       run: docker-compose -f docker-compose.yml build personal-website

  #     - name: Push Docker Image
  #       run: docker-compose -f docker-compose.yml push personal-website
  deploy:
    runs-on: self-hosted # Assuming you're using a self-hosted runner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Optional, based on your needs

      - name: Pull Docker images
        run: docker-compose -f docker-compose.yml pull personal-website

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up --force-recreate personal-website
