name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker-compose -f docker-compose.yml build personal-website

      - name: Push Docker Image
        run: docker-compose -f docker-compose.yml push personal-website
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull Docker images
        run: docker-compose -f docker-compose.yml pull personal-website

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up --force-recreate -d personal-website
